FROM python:3.9-slim

WORKDIR /app

# Install build essentials to support compiling packages if wheels are missing
RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY requirements/gateway_v2.txt .
RUN pip install --no-cache-dir -r gateway_v2.txt

COPY gateway.py .
COPY models.py .

CMD ["python", "gateway.py"]
