FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

WORKDIR /app

COPY requirements/inference.txt .
RUN pip install --no-cache-dir -r inference.txt

COPY inference.py .
COPY models.py .

CMD ["python", "inference.py"]
